### ISSUE TITLE
Start Live Document

### ISSUE THREAD

**Issue by biraj-dahal** [biraj-dahal/Team-11-Senior-Project#3]

**Comment by biraj-dahal** [comment]
[Brainstorming Wiki](https://github.com/biraj-dahal/Team-11-Senior-Project/wiki/Live-Document-%E2%80%90-Brainstorming)

**Comment by biraj-dahal** [comment]
[Google Doc](https://docs.google.com/document/d/1B7eHYhDfp5IT7181IIxYwDiFlKwmyfHWaynW9AUR5Zs/edit?usp=sharing)

**Comment by biraj-dahal** [comment]
[Live Document for Week 2 and beyond](https://docs.google.com/document/d/1ln-yKpLIupTBHF1yfGl6eUT5r1wC4ZnC11p5lZdbQLc/edit?usp=sharing)

**Comment by biraj-dahal** [comment]
M1 Live Document - Biraj, Amir, Dagmawi

**Comment by biraj-dahal** [comment]
Review - Hrishav, Suprabhat

**Comment by hri-sap** [comment]
LGTM

**Comment by suprabhatrijal** [comment]
LGTM
